title: Documentatie
email: jose.boon@maykinmedia.nl
description: >- # this means to ignore newlines until "baseurl:"
  Static site on github pages. Using this as a playground.
baseurl: "/jekyll-githubpages-playground" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  JoseJBoon

theme: minima
markdown: kramdown

collections:
  pages:
    output: true
    monkeys: "wut?" # metadata site.collections | where: "monkeys", "wut?"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

sass:
  load_paths: 
    - _sass
    - externalsource
    - nodes_modules
